title: AVAnnotate
description: AVAnnotate is the second phase of the AudiAnnotate project, which was supported by a Mellon Foundation grant awarded in 2020.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
