title: AVAnnotate
description: Documentation for AVAnnotate Project
theme: just-the-docs

url: https://github.com/hipstas

aux_links:
  Template Repository: https://github.com/hipstas

# Enable or disable heading anchors
heading_anchors: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark
